INSERT INTO actividades (id, nombre, descripcion, tipo, duracion_horas, ubicacion, provincia, distrito, imagenes, incluye, no_incluye, requisitos, edad_minima, capacidad_maxima, activo, proveedor_id, created_at, updated_at) VALUES

-- Carlos (finca.loma)
(gen_random_uuid(), 'Ruta del Cafe de Especialidad', 'Recorrido completo por fincas cafeteras de Boquete: desde la semilla hasta la taza. Incluye catacion profesional de cafes de especialidad con puntaje SCA superior a 85.', 'GASTRONOMICA', 4, 'Fincas cafeteras de Palmira, Boquete', 'Chiriqui', 'Boquete', '{}', '{"Guia especialista en cafe","Catacion de 5 variedades","Desayuno tipico","Transporte entre fincas","Bolsa de cafe para llevar"}', '{"Almuerzo","Propinas"}', '{"Ropa comoda","Protector solar","Camara fotografica"}', 0, 15, true, '02ffba96-e3e7-4364-bc4b-22c0946532b0', NOW(), NOW()),

(gen_random_uuid(), 'Ordeno y Vida de Hacienda', 'Experiencia de un dia en hacienda ganadera del interior: ordeno de vacas al amanecer, elaboracion de queso fresco, cabalgata por potreros y almuerzo tipico con fogon de lena.', 'CULTURAL', 6, 'Hacienda Los Pozos, Herrera', 'Herrera', 'Los Pozos', '{}', '{"Ordeno participativo","Taller de queso","Cabalgata 1 hora","Almuerzo tipico con fogon","Guia local"}', '{"Transporte desde la ciudad","Bebidas adicionales"}', '{"Ropa que se pueda ensuciar","Botas o zapatos cerrados"}', 5, 12, true, '02ffba96-e3e7-4364-bc4b-22c0946532b0', NOW(), NOW()),

(gen_random_uuid(), 'Ascenso Nocturno al Volcan Baru', 'Ascenso nocturno al punto mas alto de Panama (3,475 msnm) para ver el amanecer con vista simultanea al oceano Atlantico y Pacifico. Experiencia unica e inolvidable.', 'AVENTURA', 10, 'Parque Nacional Volcan Baru', 'Chiriqui', 'Boquete', '{}', '{"Guia certificado de montana","Linterna frontal","Snacks energeticos","Entrada al parque","Chocolate caliente en la cima"}', '{"Transporte al inicio del sendero","Equipo de camping","Comidas completas"}', '{"Excelente condicion fisica","Botas de senderismo","Ropa termica","Lampara frontal","Mochila con agua 2L"}', 14, 10, true, '02ffba96-e3e7-4364-bc4b-22c0946532b0', NOW(), NOW()),

-- Maria (aventura.chiriqui)
(gen_random_uuid(), 'Rafting Rio Chiriqui Viejo Clase III-IV', 'Descenso de 12 km por los rapidos del Rio Chiriqui Viejo, clasificados entre clase III y IV. Adrenalina pura rodeada de paisajes tropicales de montaña.', 'DEPORTIVA', 4, 'Rio Chiriqui Viejo, entrada por Palmira', 'Chiriqui', 'Boquete', '{}', '{"Equipo completo de rafting","Guia certificado IRF","Chaleco salvavidas","Casco","Transporte ida y vuelta","Frutas y agua"}', '{"Almuerzo","Fotos profesionales ($15 extra)","Propinas"}', '{"Saber nadar","Buena condicion fisica","Ropa que se pueda mojar","Zapatos cerrados para agua"}', 12, 8, true, 'a1516bbc-5bb7-4f45-983a-e20a91be7be4', NOW(), NOW()),

(gen_random_uuid(), 'Avistamiento de Quetzal y Aves del Bosque Nuboso', 'Caminata guiada al amanecer por senderos del bosque nuboso en busca del Quetzal Resplandeciente y mas de 50 especies de aves endemicas de las tierras altas de Panama.', 'NATURALEZA', 5, 'Senderos de Las Nubes, Cerro Punta', 'Chiriqui', 'Cerro Punta', '{}', '{"Guia ornitologico certificado","Binoculares profesionales","Lista de aves","Desayuno de campo","Transporte al sendero"}', '{"Camara con teleobjetivo","Almuerzo"}', '{"Madrugar (salida 5:00 AM)","Ropa oscura sin colores brillantes","Botas de senderismo","Silencio durante el recorrido"}', 8, 8, true, 'a1516bbc-5bb7-4f45-983a-e20a91be7be4', NOW(), NOW()),

(gen_random_uuid(), 'Canopy y Puentes Colgantes en Boquete', 'Circuito de 8 cables de canopy (tirolesa) y 4 puentes colgantes sobre el dosel del bosque tropical. Vistas aereas espectaculares del canon y cascadas.', 'AVENTURA', 3, 'Boquete Tree Trek, Alto Boquete', 'Chiriqui', 'Boquete', '{}', '{"Equipo de seguridad completo","Guias certificados","8 cables de canopy","4 puentes colgantes","Agua y snack"}', '{"Transporte","Almuerzo","Fotos ($10 extra)"}', '{"Peso entre 30-120 kg","Sin vertigo severo","Zapatos cerrados","Ropa comoda"}', 6, 12, true, 'a1516bbc-5bb7-4f45-983a-e20a91be7be4', NOW(), NOW()),

-- Roberto (agencia.panama)
(gen_random_uuid(), 'Visita Comunidad Embera - Rio Chagres', 'Navegacion en piragua por el Rio Chagres hasta la comunidad indigena Embera Puru. Danza tradicional, artesania en tagua y jagua, y almuerzo tipico indigena.', 'CULTURAL', 7, 'Rio Chagres, Parque Nacional Chagres', 'Panama', 'Chagres', '{}', '{"Transporte desde Ciudad de Panama","Piragua por el rio","Danza Embera","Taller de artesania","Almuerzo tipico","Pintura corporal con jagua"}', '{"Artesanias para compra","Propinas","Bebidas adicionales"}', '{"Traje de bano debajo de la ropa","Protector solar biodegradable","Repelente","Efectivo para artesanias"}', 4, 20, true, 'd145bc4c-6795-4b02-96a1-20b8cc16486a', NOW(), NOW()),

(gen_random_uuid(), 'Taller de Chocolate Bean-to-Bar', 'Aprende todo el proceso del chocolate artesanal: desde la cosecha del cacao hasta la tableta terminada. Incluye degustacion de 6 tipos de chocolate y un kit para llevar.', 'EDUCATIVA', 4, 'Finca de Cacao, Bocas del Toro', 'Bocas del Toro', 'Changuinola', '{}', '{"Taller completo de chocolate","Cosecha de cacao","Degustacion 6 chocolates","Kit de chocolate para llevar","Guia bilingue","Bebida de cacao"}', '{"Transporte","Almuerzo"}', '{"Ropa comoda","Zapatos cerrados para la finca"}', 0, 10, true, 'd145bc4c-6795-4b02-96a1-20b8cc16486a', NOW(), NOW()),

-- Klaudia
(gen_random_uuid(), 'Senderismo y Cascadas de El Cope', 'Caminata por senderos del Parque Nacional Omar Torrijos (El Cope) con visita a 3 cascadas escondidas. Flora y fauna del bosque tropical humedo premontano.', 'NATURALEZA', 6, 'Parque Nacional Omar Torrijos, El Cope', 'Cocle', 'La Pintada', '{}', '{"Guia naturalista local","Entrada al parque","3 cascadas","Almuerzo campestre","Bastones de senderismo","Botiquin"}', '{"Transporte desde Santiago o Penonome","Snacks adicionales"}', '{"Condicion fisica moderada","Botas de senderismo o zapatos con agarre","Ropa que se pueda mojar","Muda de ropa","Bolsa impermeable para electronica"}', 10, 12, true, '599d3b1e-5f84-419f-af9f-cfbbe047e1aa', NOW(), NOW()),

(gen_random_uuid(), 'Surf y Yoga al Amanecer en Playa Venao', 'Combo de yoga al amanecer en la playa seguido de clase de surf para todos los niveles. Incluye tabla, instructor y desayuno saludable frente al mar.', 'DEPORTIVA', 4, 'Playa Venao, Peninsula de Azuero', 'Los Santos', 'Pedasi', '{}', '{"Clase de yoga 1 hora","Clase de surf 2 horas","Tabla de surf","Instructor certificado","Desayuno saludable","Protector solar reef-safe"}', '{"Transporte","Almuerzo","Alquiler de tabla resto del dia ($10)"}', '{"Traje de bano","Toalla","Saber nadar basico","Disposicion para madrugar (5:30 AM)"}', 10, 10, true, '599d3b1e-5f84-419f-af9f-cfbbe047e1aa', NOW(), NOW());
